version: '3.8'

services:
  frontend:
    image: ghcr.io/diogenesmendes01/front-boletos-gatway:latest
    container_name: front-boletos-getway
    ports:
      - "${PORT:-3000}:80"
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://api.envio-boleto.olympiabank.xyz}
      - VITE_MOCK_MODE=${VITE_MOCK_MODE:-false}
      - VITE_APP_ENVIRONMENT=${VITE_APP_ENVIRONMENT:-production}
    restart: unless-stopped
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.olympiabank.service=frontend"
      - "com.olympiabank.environment=${ENVIRONMENT:-production}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy-network:
    external: true
    name: proxy-network
