name: Deploy React Frontend

on:
  push:
    branches: [main, master]
  workflow_dispatch:  # Permite execução manual

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }}
            VITE_MOCK_MODE=${{ vars.VITE_MOCK_MODE }}
            VITE_APP_ENVIRONMENT=${{ vars.VITE_APP_ENVIRONMENT }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script_stop: true
          script: |
            # Verificar se o diretório existe
            if [ ! -d "/opt/front-boletos-getway" ]; then
              echo "❌ Diretório não existe. Execute o script setup-vps.sh primeiro!"
              exit 1
            fi
            
            cd /opt/front-boletos-getway
            
            # Login no GitHub Container Registry
            echo "🔐 Fazendo login no GitHub Container Registry..."
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Fazer backup antes do deploy
            if [ -f "backup.sh" ]; then
              ./backup.sh || true
            fi
            
            # Pull da nova imagem
            echo "📥 Baixando nova imagem..."
            if docker compose version >/dev/null 2>&1; then 
              COMPOSE="docker compose"
            else 
              COMPOSE="docker-compose"
            fi
            
            $COMPOSE pull
            
            # Restart com zero downtime
            echo "🔄 Reiniciando aplicação..."
            $COMPOSE up -d --no-deps --force-recreate frontend
            
            # Limpar imagens antigas
            docker image prune -f
            
            # Verificar saúde do container
            echo "🏥 Verificando health check..."
            sleep 5
            if docker ps | grep -q "front-boletos-getway"; then
              echo "✅ Deploy concluído com sucesso!"
            else
              echo "❌ Erro no deploy, verificando logs..."
              docker logs front-boletos-getway --tail 50
              exit 1
            fi
